### ISSUE TITLE
Add verbiage that OData 4 is not supported

### ISSUE THREAD

**Issue by tschettler** [Breeze/breeze.github.io#2]
The current documentation indicates that you can use breeze with OData 4 by configuring the adapter instance (http://breeze.github.io/doc-js/server-odata.html). After a lot of trial and error, I found that this is not true (confirmed here: http://stackoverflow.com/a/28547060). 

It also states that the adapter depends on datajs, but datajs doesn't support OData 4, while the odatajs library is the OData 4 supporting javascript library, but is not specified as required by the webApiOData4 adapter.

**Comment by wardbell** [comment]
Thanks for prodding. Done. See revised http://breeze.github.io/doc-js/server-odata.html
